spin_version = "1"
name = "finicky-whiskers"
version = "1.1.0"
trigger = { type = "http", base = "/" }

[variables]
jsonbin_id = { required = true }
master_key = { required = true }
access_key = { required = true }

# Serve static files
[[component]]
id = "fileserver"
source = "components/fileserver.wasm"
files = [{ source = "site", destination = "/" }]
[component.trigger]
route = "/..."

# Redirect / to /index.html
[[component]]
id = "redirect-to-index"
source = "components/redirect.wasm"
environment = { DESTINATION = "/index.html" }
[component.trigger]
route = "/"
executor = { type = "wagi" }

# Tally an individual event
[[component]]
id = "tally"
source = "components/tally.wasm"
environment = {REDIS_ADDRESS = "redis://localhost:6379/", REDIS_CHANNEL = "fw-tally"}
[component.trigger]
route = "/tally"

# Initialize session data
[[component]]
id = "session"
source = "session/session.wasm"
[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/session.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/session"

# Get the scores for a particular game
[[component]]
id = "scoreboard"
source = "components/scoreboard.wasm"
environment = {REDIS_ADDRESS = "redis://localhost:6379/"}
[component.trigger]
route = "/score"

# Stores a highscore in JSOBbin.io
[[component]]
id = "highscore"
source = "components/highscore.wasm"
allowed_http_hosts = [ "https://api.jsonbin.io" ]
[component.trigger]
route = "/highscore"
[component.config]
jsonbin_endpoint = "https://api.jsonbin.io/v3/b/{{ jsonbin_id }}"
master_key = "{{ master_key }}"
access_key = "{{ access_key }}"