spin_version = "1"
name = "finicky-whiskers-redis"
trigger = { type = "redis", address = "redis://localhost:6379" }
version = "0.1.0"

[[component]]
id = "morsel-event"
source = "target/wasm32-wasi/release/morsel_event.wasm"
[component.trigger]
channel = "fw-tally"